#%RAML 1.0
title: customer-accounts-SAPI

/accounts:
  get:
    headers:
      requestor_id:
    queryParameters:
      account_type:
        enum: [personal,business]
      name: 
    responses:
      200:
        body:
          application/json:
            type: Accounts[]
            example: !include /example/account-example.json
  post:
    body:
      application/json:
        type: Accounts
        example: !include /example/account-post-example.json
          
      
              