#%RAML 1.0
title: customer-accounts-SAPI

types:
  Accounts: !include /dataType/accounts_dataType.raml

/accounts:
  get:
    headers:
      requestor_id:
        description: The person or system requesting the data
        displayName: Requestor ID
    queryParameters:
      account_type:
        enum: [personal,business]
      name: 
    responses:
      200:
        body:
          application/json:
            type: Accounts[]
            example: !include /examples/account_example.json
  post:
    body:
      application/json:
        type: Accounts
        example: !include /examples/account_post_example.json
    responses:
      201:
        body:
          application/json:
            example: {"message" : "Account created"}
              
            
