#%RAML 1.0 DataType

type: object
values:

"Id": 1234,
"Name": "Intell V",
"Type": "business",
"Address": "12345 Green st ,Boulder ,Colorado ,82433 ,USA",
"Airmiles": 1000,
"Creationdate": "10/14/2023"